### ISSUE TITLE
Toggle Muter accidentally activates the “Alt” key

### ISSUE THREAD

**Issue by huangguan1993** [drewmarsh/toggle-muter#1]
Thanks drewmarsh for creating this amazing software.
![image](https://github.com/drewmarsh/toggle-muter/assets/73452695/67cd644a-72f2-4c20-a4ab-9f6fbfc90ac5)
but I try to use the default settings, like Control + Q, it works perfectly without accidentally activating the "Alt" key.

**Comment by drewmarsh** [comment]
Are you sure F10 doesn't just activate that toolbar even without the program running? I just closed Toggle Muter and tested both F10 and the ALT key. They both cause activation on this toolbar for me as well. It might just be a keybind collision.

**Comment by huangguan1993** [comment]
OMG, Sorry, big apologies..
I didn't realize this, thanks drewmarsh for the quick response, I'll try to use another combination key
